# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hash_name.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fhash_name.proto\x12\thash_name\"m\n\x0fHashNameRequest\x12\x14\n\x0c\x64\x65sired_name\x18\x01 \x01(\t\x12\x1e\n\x16ideal_hamming_distance\x18\x02 \x01(\x05\x12$\n\x1cinteresting_hamming_distance\x18\x03 \x01(\x05\"Q\n\x10HashNameResponse\x12\x0e\n\x06secret\x18\x01 \x01(\t\x12\x13\n\x0bhashed_name\x18\x02 \x01(\t\x12\x18\n\x10hamming_distance\x18\x03 \x01(\x05\x32\x99\x01\n\nHashFinder\x12\x41\n\x04\x46ind\x12\x1a.hash_name.HashNameRequest\x1a\x1b.hash_name.HashNameResponse\"\x00\x12H\n\tFindRange\x12\x1a.hash_name.HashNameRequest\x1a\x1b.hash_name.HashNameResponse\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hash_name_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_HASHNAMEREQUEST']._serialized_start=30
  _globals['_HASHNAMEREQUEST']._serialized_end=139
  _globals['_HASHNAMERESPONSE']._serialized_start=141
  _globals['_HASHNAMERESPONSE']._serialized_end=222
  _globals['_HASHFINDER']._serialized_start=225
  _globals['_HASHFINDER']._serialized_end=378
# @@protoc_insertion_point(module_scope)
